version: '2'
services:
  canvas:
    image: asynchronyringo/canvaslms
    command: script/start_canvas.rb
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/app
      - ./gems/plugins/spark_plugin:/usr/src/app/gems/plugins/spark_plugin
      - ./config/:/usr/src/app/config/
      - ./script:/usr/src/app/script/
      - ./public/javascripts/context_modules.js:/usr/src/app/public/javascripts/context_modules.js
      - ./public/javascripts/select_content_dialog.js:/usr/src/app/public/javascripts/select_content_dialog.js
    environment:
      UNICORN_PROCESSES: 4
    env_file:
      - common.env
      - canvas.env
    depends_on:
      - db
      - redis
  jobs:
    command: bash -c "script/wait-for-it.sh -t 60 db:5432 -- sleep 60 && bundle exec script/delayed_job run"
    image: asynchronyringo/canvaslms
    env_file:
      - common.env
      - canvas.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.3
    env_file:
      - common.env
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data/canvaslms
  redis:
    image: redis:3
  mail:
    image: elsdoerfer/exim-sender
    expose:
      - "25"
    environment:
      ALLOWED_HOSTS: "*"
    env_file:
      - mail.env
