version: '2'
services:
  canvas:
    image: asynchronyringo/canvaslms
    command: bash -c "./wait-for-it.sh -t 60 db:5432 -- bundle exec rake db:create && bundle exec rake db:initial_setup && ./node_modules/.bin/brandable_css && bundle exec unicorn -p 3000 -c config/unicorn.rb"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/app
      - ./gems/plugins/spark_plugin:/usr/src/app/gems/plugins/spark_plugin
      - ./custom_docker/cache_store.yml:/usr/src/app/config/cache_store.yml
      - ./custom_docker/database.yml:/usr/src/app/config/database.yml
      - ./custom_docker/delayed_jobs.yml:/usr/src/app/config/delayed_jobs.yml
      - ./custom_docker/domain.yml:/usr/src/app/config/domain.yml
      - ./custom_docker/outgoing_mail.yml:/usr/src/app/config/outgoing_mail.yml
      - ./custom_docker/security.yml:/usr/src/app/config/security.yml
    environment:
      UNICORN_PROCESSES: 4 
    env_file:
      - common.env
      - canvas.env
    depends_on:
      - db
      - redis
  jobs:
    command: bash -c "./wait-for-it.sh -t 60 db:5432 -- sleep 60 && bundle exec script/delayed_job run"
    image: asynchronyringo/canvaslms
    env_file:
      - common.env
      - canvas.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.3
    env_file:
      - common.env
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data/canvaslms
  redis:
    image: redis:3
  mail:
    image: elsdoerfer/exim-sender
    expose:
      - "25"
    environment:
      ALLOWED_HOSTS: "*"
    env_file:
      - mail.env
