FROM ubuntu:14.04
##FROM ruby:2.3
# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Dependency and Node installation
RUN apt-get update -qq \
    && apt-get -y install curl software-properties-common \
    && add-apt-repository -y ppa:brightbox/ruby-ng \
    && apt-get update -qq \
    && apt-get install -y build-essential libpq-dev ruby-dev zlib1g-dev libxml2-dev libxslt1-dev libhttpclient-ruby imagemagick libxmlsec1-dev python-software-properties libpq-dev libpqxx-dev libglib2.0 libssl-dev sqlite3 ruby2.3 ruby2.3-dev git
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

# Localization env
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Workfolder creation and setup
RUN mkdir /var/canvas
WORKDIR /var/canvas
# File Copy of full canvas code
COPY . /var/canvas

RUN apt-get install libsqlite3-dev

# Gem installation
RUN gem install bundler rake
RUN bundle install --without mysql --path vendor/bundle

# npm
RUN npm install


# Copy of configuration files

# Database config requires ENV variables
# POSTGRES_USER
# POSTGRES_PASSWORD
# DB_HOST - Hostname for the database server
COPY custom_docker/database.yml config/database.yml
# Domain config requires ENV variables
# DOMAIN - eg: subdomain.domain.com

# Outgoing mail configured to use 'test' method
COPY custom_docker/outgoing_mail.yml config/outgoing_mail.yml

COPY custom_docker/domain.yml config/domain.yml
# Security config requires ENV variables
# ENCRYPTION_KEY
COPY custom_docker/security.yml config/security.yml

COPY custom_docker/cache_store.yml config/cache_store.yml

# Initial database setup for production
# Requires preset ENV variables
# CANVAS_LMS_ADMIN_EMAIL
# CANVAS_LMS_ADMIN_PASSWORD
# CANVAS_LMS_ACCOUNT_NAME
# CANVAS_LMS_STATS_COLLECTION
## Moved to docker-compose.setup.yml
##RUN RAILS_ENV=production bundle exec rake db:initial_setup

## User access and file security relating to users
# Create a Canvas user
RUN adduser --disabled-password --gecos canvas canvasuser

# Setup assets folder and ownership to new user
RUN mkdir -p log tmp/pids public/assets public/stylesheets/compiled
RUN touch Gemfile.lock
RUN chown -R canvasuser config/environment.rb log tmp public/assets \
        public/stylesheets/compiled Gemfile.lock config.ru

# Compile assets
## Moved to docker-compose.setup.yml
##RUN RAILS_ENV=production bundle exec rake canvas:compile_assets

# Restrict config files to canvasuser
RUN chown canvasuser config/*.yml
RUN chmod 400 config/*.yml
