development:
  delivery_method: "test"
  address: <%= ENV["CANVAS_SMTP_HOST"] %>
  port: <%= ENV["CANVAS_SMTP_PORT"] || "25" %>
  user_name: ""
  password: ""
  domain: <%= ENV["DOMAIN"] %>
  outgoing_address: <%= "donotreply@" + ENV["DOMAIN"] %>
  default_name: "Canvas"
  openssl_verify_mode: "none"

test:
  delivery_method: "test"

production:
  address: "mail"
  port: "<%= ENV["CANVAS_SMTP_PORT"] || "25" %>"
  domain: <%= ENV["DOMAIN"] %>
  outgoing_address: <%= "donotreply@" + ENV["DOMAIN"] %>
  default_name: "Canvas"
